# Generated by Django 5.0.4 on 2024-04-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Notes',
        ),
    ]
