# Generated by Django 5.0.4 on 2024-05-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tribe', '0002_rename_note_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('resource_image', models.ImageField(upload_to='')),
                ('max_storage_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stored_resource_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stored_resource_quantity_at_time', models.DateTimeField()),
                ('production_per_second', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumption_per_second', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_production_per_second', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_unit_weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
