# Generated by Django 5.0.4 on 2024-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tribe', '0003_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='consumption_per_second',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='max_storage_capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='net_production_per_second',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='one_unit_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='production_per_second',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='stored_resource_quantity',
            field=models.FloatField(),
        ),
    ]
