# Generated by Django 5.0.4 on 2024-05-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tribe', '0004_alter_resources_consumption_per_second_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='consumption_per_second',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='max_storage_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='net_production_per_second',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='one_unit_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='production_per_second',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='stored_resource_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
